### ISSUE TITLE
bug: Virtual text gets messed up when any new code is added to the buffer

### ISSUE THREAD

**Issue by eslam-allam** [maxandron/goplements.nvim#4]
### Neovim version (nvim -v)

NVIM v0.11.0-dev+504-gaa853f362

### Operating system/version

Fedora 40

### Describe the bug

When I type something on top of an interface (bumping the interface down), the virtual text for implementations deforms. Deleting the text that bumped it down or toggling the plugin off/on seems to solve the issue but not always.

Here's an illustration of how that looks like:

[Screencast from 2024-07-30 20-12-53.webm](https://github.com/user-attachments/assets/44f7d780-89e7-46c3-8d7a-c78d568a304d)

Edit: This seems to only affect interfaces not the implementing structs

### Steps To Reproduce

1. Go to an interface that is implemented by multiple structs.
2. Add text any where in the same buffer
3. The virtual text should be messed up now.
4. Remove the text that caused this issue.
5. Virtual text should be ok now (no always)

### Expected Behavior

The virtual text shouldnt be affected by typing in the buffer.

**Comment by maxandron** [comment]
Thanks for opening the bug! It doesn't happen for me on vim 0.10. I'll try to reproduce with 0.11

**Comment by maxandron** [comment]
Thanks for reporting the bug! I managed to reproduce it. Fixing now

**Comment by maxandron** [comment]
Done. Thank you for reporting this!
Let me know if you encounter any other issues
